include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/data/**

linter:
   rules:
     - annotate_overrides
     - avoid_bool_literals_in_conditional_expressions
     - avoid_function_literals_in_foreach_calls
     - avoid_null_checks_in_equality_operators
#     - avoid_print # ensure all calls are rationalized (and silence-able)
     - avoid_private_typedef_functions
     - avoid_redundant_argument_values
     - await_only_futures
     - camel_case_types
     - comment_references
     - depend_on_referenced_packages
     - directives_ordering
     - empty_statements
     - hash_and_equals
     - implementation_imports
     - non_constant_identifier_names
     - omit_local_variable_types
     - prefer_adjacent_string_concatenation
     - prefer_collection_literals
     - prefer_conditional_assignment
     - prefer_expression_function_bodies
     - prefer_final_fields
     - prefer_for_elements_to_map_fromIterable
     - prefer_function_declarations_over_variables
     - prefer_generic_function_type_aliases
     - prefer_if_null_operators
     - prefer_initializing_formals
     - prefer_inlined_adds
     - prefer_interpolation_to_compose_strings
     - prefer_mixin
     - prefer_null_aware_operators
     - prefer_relative_imports
     - prefer_single_quotes
     - prefer_spread_collections
     - prefer_void_to_null
     - provide_deprecation_message
     - test_types_in_equals
     - throw_in_finally
     - unawaited_futures
     - unnecessary_brace_in_string_interps
     - unnecessary_final
     - unnecessary_getters_setters
     - unnecessary_lambdas
     - unnecessary_overrides
     - unnecessary_parenthesis
     - unnecessary_statements
     - unnecessary_this
     - use_full_hex_values_for_flutter_colors
     - use_function_type_syntax_for_parameters
     - use_string_buffers
     - void_checks
