# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - test/data/**

linter:
   rules:
     - annotate_overrides
     - camel_case_types
     - empty_statements
     - hash_and_equals
     - non_constant_identifier_names
     - prefer_expression_function_bodies
     - prefer_relative_imports
     - prefer_single_quotes
     - test_types_in_equals
     - throw_in_finally
     - unnecessary_brace_in_string_interps
     - unnecessary_lambdas
     - unnecessary_statements
     - unnecessary_this
