name: doc_surveyor
description: Sample project that computes missing API doc stats.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  path: ^1.8.0
  surveyor:
    path: ../..

dev_dependencies:
  lints: ^2.0.0
