name: doc_surveyor
description: Sample project that computes missing API doc stats.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  surveyor:
    path: ../..

dev_dependencies:
  lints: ^1.0.0
