name: widget_surveyor
description: Sample project that performs widget surveying.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^5.4.0
  cli_util: ^0.4.0
  corpus:
    # update when published
    git: https://github.com/pq/corpus
  path: ^1.8.0
  surveyor:
    path: ../..

dev_dependencies:
  lints: ^2.0.0
  test: ^1.14.0
