name: widget_surveyor
description: Sample project that performs widget surveying.

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  analyzer: ^0.39.4
  corpus:
    # update when published
    git: git://github.com/pq/corpus.git
  surveyor:
    # update when published
    git:
      url: git://github.com/pq/surveyor.git
      ref: 7ffa98e549aa88c5beabde7aec30d44dd1323c3b

dev_dependencies:
  lints: ^1.0.0
  test: ^1.14.0
